import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pw Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        
      <div className={styles.container}>Esto es una prueba</div>
      <a href="https://piensaenweb.com">Haz clic aquí</a>

      </main> 

      <footer className={styles.footer}>
        <span>Desarrollado por Piensaenweb</span> 
      </footer>
    </div>
  )
}
